### ISSUE TITLE
metalsmith.json is malformed.

### ISSUE THREAD

**Issue by luckypoem** [mrkiffie/mrkiffie.com#1]
hi.

root@AR:~/mrkiffie.com-site# ls
build	  metalsmith.json  package.json  scripts
build.js  node_modules	   README.md	 src
root@AR:~/mrkiffie.com-site# cat metalsmith.json
{
    "source": "src",
    "destination": "build",
    "plugins": {
        "metalsmith-drafts": true,
        "metalsmith-markdown": true,
        "metalsmith-layouts": {
            engine: "handlebars"
        }
    }
}
root@AR:~/mrkiffie.com-site# metalsmith

  Metalsmith · it seems like metalsmith.json is malformed.

root@AR:~/mrkiffie.com-site#

how to fix it?
thank you.

**Comment by mrkiffie** [comment]
Hi @luckypoem - nice username 😄 

The problem with that `metalsmith.json` file is that `engine` is missing the double quotes - `"engine"`.

Try this:
```
{
  "source": "src",
  "destination": "build",
  "plugins": {
    "metalsmith-drafts": true,
    "metalsmith-markdown": true,
    "metalsmith-layouts": {
      "engine": "handlebars"
    }
  }
}
```

Let me know if that helps you get further.
